project_id = "wklmkaqeqwwgjbgrscys"

[functions.listar-vouchers]
verify_jwt = false

[functions.buscar-voucher]
verify_jwt = false

[functions.criar-checkout]
verify_jwt = false

[functions.webhook-stripe]
verify_jwt = false
